<?php

namespace App\Console\Commands;

use Exception;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class SeedTourData extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'command:seed-tour-data';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Seed data into tours, tour_images, areas, hotels, vehicles, drivers, and tour_guides tables';

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        try {
            DB::transaction(function () {
                $this->seedAreasTable();
                $this->seedHotelsTable();
                $this->seedVehiclesTable();
                $this->seedDriversTable();
                $this->seedTourGuidesTable();
                $this->seedToursTable();
                $this->seedTourImagesTable();
                $this->seedTourDatesTable();
            });

            $this->info('Seeded data into all tables successfully.');
        } catch (Exception $e) {
            $this->error('Failed to seed data: ' . $e->getMessage());
        }
    }

    /**
     * Seed data for areas table
     *
     * @return void
     */

     
    private function seedAreasTable()
    {
        $areas = [
            ['id' => 1, 'name' => 'Hà Nội', 'thumbnail' => 'images/ha_noi.jpg'],
            ['id' => 2, 'name' => 'TP. Hồ Chí Minh', 'thumbnail' => 'images/ho_chi_minh.jpg'],
            ['id' => 3, 'name' => 'Đà Nẵng', 'thumbnail' => 'images/da_nang.jpg'],
            ['id' => 4, 'name' => 'Hội An', 'thumbnail' => 'images/hoi_an.jpg'],
            ['id' => 5, 'name' => 'Huế', 'thumbnail' => 'images/hue.jpg'],
            ['id' => 6, 'name' => 'Nha Trang', 'thumbnail' => 'images/nha_trang.jpg'],
            ['id' => 7, 'name' => 'Hà Giang', 'thumbnail' => 'images/ha_giang.jpg'],
            ['id' => 8, 'name' => 'Phú Quốc', 'thumbnail' => 'images/phu_quoc.jpg'],
            ['id' => 9, 'name' => 'Sa Pa', 'thumbnail' => 'images/sapa.jpg'],
            ['id' => 10, 'name' => 'Hạ Long', 'thumbnail' => 'images/quang_ninh.jpg'],
        ];

        DB::table('areas')->insert($areas);
        $this->info('Seeded areas table successfully.');
    }

    /**
     * Seed data for hotels table
     *
     * @return void
     */
    private function seedHotelsTable()
    {
        $hotels = [
            [
                'id' => 1,
                'name' => 'Intercontinental Danang Sun Peninsula Resort',
                'address' => 'Phường Thọ Quang, Bán Đảo Sơn Trà, TP. Đà Nẵng',
                'stars' => 5,
                'phone' => '023 6393 8888',
                'description' => 'Khu nghỉ dưỡng hàng đầu của IHG tại Việt Nam khai trương vào tháng 6 năm 2012, với diện tích 39 ha sườn núi được bảo tồn cẩn trọng trong Khu Bảo Tồn Tự nhiên Bán đảo Sơn Trà. Khu nghỉ dưỡng sang trọng bao gồm 201 phòng nằm ẩn mình trong khu rừng hoang sơ với tầm nhìn hướng ra Vịnh Bãi Bắc, nơi có bãi biển hoang sơ dài 700m và được vinh danh là một trong những bãi biển đẹp nhất Việt Nam. InterContinental Danang Sun Peninsula Resort chắc chắn là điểm nghỉ dưỡng mà bạn không nên bỏ qua.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'La Veranda Resort Phú Quốc – MGallery',
                'address' => 'Trần Hưng Đạo, TP. Phú Quốc, Kiên Giang',
                'stars' => 5,
                'phone' => '038 323 1234',
                'description' => 'Mỗi khu nghỉ boutique thuộc thương hiệu MGallery là một câu chuyện đặc biệt, nơi du khách có thể đắm chìm trong những hành trình kỳ thú về phiêu lưu, lãng mạn, lịch sử, văn hóa, thiên nhiên và nhiều trải nghiệm khác nhau trong mỗi kỳ nghỉ đáng nhớ. Khách sạn La Veranda Phú Quốc xây dựng theo phong cách dinh thự Pháp thập niên 1920, tọa lạc giữa khu vườn nhiệt đới bên bãi biển dài xanh mát. La Veranda có 70 phòng tiêu chuẩn 5 sao quốc tế, 2 nhà hàng, một quán bar, bể bơi, khu vui chơi thể thao nước và spa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'JW Marriott Hotel Hanoi',
                'address' => '8 Đỗ Đức Dục, Quận Nam Từ Liêm, TP. Hà Nội',
                'stars' => 5,
                'phone' => '024 3833 5588',
                'description' => 'Không thể không nhắc đến JW Marriott Hotel Hanoi trong danh sách những khách sạn tuyệt vời nhất Việt Nam. Với sự đánh giá cao từ khách hàng và vị trí đắc địa tại trung tâm thủ đô Hà Nội, JW Marriott Hotel Hanoi mang đến trải nghiệm sang trọng và đẳng cấp. Với thiết kế hiện đại, dịch vụ đạt chuẩn quốc tế, khách sạn JW Marriott Hanoi cam kết mang lại dịch vụ hoàn hảo nhất cho du khách.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'The Reverie Saigon',
                'address' => 'Tòa nhà Times Square 22-36 Nguyễn Huệ, Quận 1, TP. HCM',
                'stars' => 5,
                'phone' => '028 3823 6688',
                'description' => 'The Reverie Saigon được biết đến là biểu tượng của sự xa hoa và là thành viên độc nhất vô nhị của Tổ Chức Các Khách Sạn Hàng Đầu Thế Giới tại Việt Nam. Nằm tại vị trí đắc địa trên tòa nhà Times Square nổi tiếng, quận 1, khách sạn này không chỉ mang đến dịch vụ hàng đầu thế giới mà còn gây ấn tượng với thiết kế nội thất phong cách Ý tinh tế và sang trọng độc đáo. Với dịch vụ chuyên nghiệp, tiện nghi hiện đại và không gian lộng lẫy, hãy tận hưởng mọi khoảnh khắc nghỉ ngơi tại The Reverie Saigon. Không chỉ là nơi nghỉ, đây còn là một tác phẩm nghệ thuật sống với phong cách pha trộn giữa Á và Âu.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Vinpearl Luxury Nha Trang',
                'address' => 'Đảo Hòn Tre, Phường Vĩnh Nguyên, TP. Nha Trang, Khánh Hòa',
                'stars' => 5,
                'phone' => '1900 232 389',
                'description' => 'Vinpearl Luxury Nha Trang là điểm đến không thể bỏ lỡ với những du khách trân trọng từng khoảnh khắc bình yên bên người thương. Nằm bên bờ biển thiên đàng, 84 căn biệt thự tinh tế tọa lạc giữa khu vườn nhiệt đới xanh mát, lắng nghe nhịp sống nhẹ nhàng của sóng biển như bản nhạc êm dịu của thiên nhiên, tạo nên không gian yên bình và ấm cúng như một \'ốc đảo hạnh phúc\' xa xôi khỏi cuộc sống hối hả ở thành phố.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Pullman Hanoi',
                'address' => '40 Cát Linh, Quận Đống Đa, TP. Hà Nội',
                'stars' => 5,
                'phone' => '024 3733 0688',
                'description' => 'Khách sạn Pullman Hà Nội là điểm đến sang trọng không thể bỏ qua tại trung tâm thủ đô Hà Nội, với kiến trúc và thiết kế không kém phần đẳng cấp so với các khách sạn thế giới. Cho dù bạn đến để nghỉ ngơi hay công tác, Pullman luôn là lựa chọn hoàn hảo cho kỳ nghỉ của bạn. Với vị trí thuận lợi tại góc đường Cát Linh và Trung tâm Triển lãm Giảng Võ, khách sạn gần các cơ quan chính phủ, đại sứ quán và trung tâm thương mại.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'InterContinental Hanoi Landmark72',
                'address' => 'Tòa nhà Hanoi Landmark72 Lô E6, Quận Nam Từ Liêm, TP. Hà Nội',
                'stars' => 5,
                'phone' => '024 3698 8888',
                'description' => 'InterContinental Hanoi Landmark72 là đỉnh cao của sự sang trọng tại Hà Nội với chiều cao hơn 346m. Với 358 phòng nghỉ tiện nghi, 5 nhà hàng và bar sáng tạo, khách sạn mang đến trải nghiệm ẩm thực tinh tế và tầm nhìn toàn cảnh thành phố. Với cơ sở vật chất hàng đầu cho sự kiện và hội nghị, cùng Club InterContinental Lounge lớn nhất Đông Nam Á, InterContinental Hanoi Landmark72 hứa hẹn dịch vụ chuyên nghiệp và cá nhân hóa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Vinpearl Resort & Spa Hạ Long',
                'address' => 'Đảo Rều, Bãi Cháy, Thành phố Hạ Long, Tỉnh Quảng Ninh',
                'stars' => 5,
                'phone' => '020 3385 7858',
                'description' => 'Với vẻ đẹp kiến trúc lâu đài độc đáo, Vinpearl Resort & Spa Hạ Long là điểm đến lý tưởng tại miền Bắc Việt Nam, nằm trên bãi biển, nhấn chìm trong không gian huyền bí của vịnh Hạ Long. Thiết kế sang trọng, 3 bãi biển riêng tư, hồ bơi rộng lớn tạo nên không gian nghỉ dưỡng tuyệt vời. Phòng nghỉ rộng rãi với ban công lớn mang đến trải nghiệm đắm chìm trong vẻ đẹp của thành phố Hạ Long và biển cả.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Park Hyatt Saigon',
                'address' => '2 Công Trường Lam Sơn, Bến Nghé, Quận 1, TP. HCM',
                'stars' => 5,
                'phone' => '028 3824 1234',
                'description' => 'Được vinh danh trong danh sách 500 khách sạn hàng đầu thế giới, Park Hyatt Saigon kết hợp văn hóa Việt truyền thống và kiến trúc hiện đại, mang đến trải nghiệm sang trọng với dịch vụ đẳng cấp quốc tế. Tọa lạc trên Quảng trường Lam Sơn, chỉ cách sân bay Tân Sơn Nhất 7.5km, khách sạn đem đến vị trí trung tâm thuận lợi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Hanoi La Siesta Central & Spa',
                'address' => '94 Mã Mây, Quận Hoàn Kiếm, TP. Hà Nội',
                'stars' => 4,
                'phone' => '024 3926 3641',
                'description' => 'Hanoi La Siesta Central Hotel & Spa là địa điểm lý tưởng cho du khách quốc tế. Nằm trong bán kính 300 m từ Đền Ngọc Sơn và 700 m từ Ô Quan Chưởng. Mọi phòng tại Hanoi La Siesta Central Hotel & Spa đều trang bị đầy đủ tiện nghi hiện đại như bàn ghế, TV màn hình phẳng, phòng tắm riêng, máy điều hòa, bàn làm việc và máy pha cà phê. Bảo đảm thoải mái và tiện nghi khi lưu trú.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ];

        DB::table('hotels')->insert($hotels);
        $this->info('Seeded hotels table successfully.');
    }

    /**
     * Seed data for vehicles table
     *
     * @return void
     */
    private function seedVehiclesTable()
    {
        $vehicles = [
            [
                'id' => 1,
                'type' => 'Bus',
                'model' => 'Volvo 7900 Hybrid',
                'license_plate' => '44A-01734',
                'capacity' => 58,
                'driver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'type' => 'Bus',
                'model' => 'Golden Dragon XML6102',
                'license_plate' => '45C-01845',
                'capacity' => 52,
                'driver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'type' => 'Bus',
                'model' => 'Hyundai Aero City',
                'license_plate' => '29B-00123',
                'capacity' => 50,
                'driver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'type' => 'Bus',
                'model' => 'Mercedes-Benz Intouro',
                'license_plate' => '29B-00456',
                'capacity' => 55,
                'driver_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'type' => 'Car',
                'model' => 'Toyota Camry',
                'license_plate' => '51D-12345',
                'capacity' => 5,
                'driver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'type' => 'Car',
                'model' => 'Honda Civic',
                'license_plate' => '52E-23456',
                'capacity' => 5,
                'driver_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'type' => 'Aircraft',
                'model' => 'Boeing 737',
                'license_plate' => '03B-56789',
                'capacity' => 200,
                'driver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'type' => 'Aircraft',
                'model' => 'Airbus A320',
                'license_plate' => '04C-67890',
                'capacity' => 180,
                'driver_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'type' => 'Train',
                'model' => 'Shinkansen N700',
                'license_plate' => '15F-98765',
                'capacity' => 600,
                'driver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'type' => 'Train',
                'model' => 'Eurostar E320',
                'license_plate' => '16G-87654',
                'capacity' => 500,
                'driver_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('vehicles')->insert($vehicles);
        $this->info('Seeded vehicles table successfully.');
    }

    /**
     * Seed data for drivers table
     *
     * @return void
     */
    private function seedDriversTable()
    {
        $drivers = [
            [
                'name' => 'Driver 1',
                'avatar' => 'path/to/avatar1.jpg',
                'phone' => '55511234',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            

            
        ];

        DB::table('drivers')->insert($drivers);
        $this->info('Seeded drivers table successfully.');
    }

    /**
     * Seed data for tour_guides table
     *
     * @return void
     */
    private function seedTourGuidesTable()
    {
        $tourGuides = [
            [
                'id' => 1,
                'name' => 'Nguyễn Đình Thắng',
                'avatar' => 'path/to/avatar1.jpg',
                'phone' => '555-1111',
                'email' => 'nguyendinhthang@gmail.com',
                'bio' => 'Nguyễn Đình Thắng là một hướng dẫn viên có kinh nghiệm lâu năm trong ngành du lịch. Anh có niềm đam mê sâu sắc với lịch sử và văn hóa địa phương. Với sự am hiểu sâu rộng và sự nhiệt huyết, Nguyễn Đình Thắng luôn mang lại trải nghiệm độc đáo và đáng nhớ cho khách du lịch.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Trần Thị Hương',
                'avatar' => 'path/to/avatar2.jpg',
                'phone' => '555-2222',
                'email' => 'huongtran@gmail.com',
                'bio' => 'Trần Thị Hương là một hướng dẫn viên năng động và thân thiện, có khả năng giao tiếp tốt và sự hiểu biết sâu sắc về các điểm tham quan địa phương. Với kinh nghiệm dày dặn và sự quan tâm tận tâm đến từng chi tiết, Hương luôn đảm bảo du khách có một chuyến đi thú vị và an toàn.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Lê Văn Nam',
                'avatar' => 'path/to/avatar3.jpg',
                'phone' => '555-3333',
                'email' => 'namle@gmail.com',
                'bio' => 'Lê Văn Nam là một hướng dẫn viên tài năng với khả năng tổ chức tuyệt vời và sự chăm sóc tận tâm đến từng khách hàng. Nam có kinh nghiệm dày dặn trong việc dẫn tour và biết cách kết nối với mọi đối tượng khách hàng. Anh luôn mong muốn mang lại cho du khách những kỷ niệm đáng nhớ và những trải nghiệm đầy ý nghĩa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Phạm Thị Mai',
                'avatar' => 'path/to/avatar4.jpg',
                'phone' => '555-4444',
                'email' => 'maipham@gmail.com',
                'bio' => 'Phạm Thị Mai là một hướng dẫn viên có sự nhiệt huyết và khả năng giao tiếp tuyệt vời. Với sự am hiểu sâu rộng về văn hóa địa phương và lịch sử, Mai luôn mang đến cho du khách những trải nghiệm đáng nhớ và kiến thức bổ ích.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Nguyễn Văn Hùng',
                'avatar' => 'path/to/avatar5.jpg',
                'phone' => '555-5555',
                'email' => 'hungnguyen@gmail.com',
                'bio' => 'Nguyễn Văn Hùng là một hướng dẫn viên nhiệt huyết với đam mê khám phá và chia sẻ kiến thức. Anh có kinh nghiệm phong phú trong lĩnh vực du lịch và luôn nỗ lực mang đến cho du khách những trải nghiệm tuyệt vời nhất.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Hoàng Thị Lan',
                'avatar' => 'path/to/avatar6.jpg',
                'phone' => '555-6666',
                'email' => 'lanhoang@gmail.com',
                'bio' => 'Hoàng Thị Lan là một hướng dẫn viên chuyên nghiệp với kinh nghiệm lâu năm trong việc dẫn dắt tour du lịch. Với sự quan tâm tận tâm và kiến thức sâu rộng về các địa danh du lịch, Lan luôn mang đến cho du khách những trải nghiệm đầy ý nghĩa và đáng nhớ.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Đỗ Minh Tuấn',
                'avatar' => 'path/to/avatar7.jpg',
                'phone' => '555-7777',
                'email' => 'tuando@gmail.com',
                'bio' => 'Đỗ Minh Tuấn là một hướng dẫn viên tài năng với khả năng tổ chức và giao tiếp xuất sắc. Anh có niềm đam mê sâu sắc với lịch sử và văn hóa địa phương, luôn mong muốn chia sẻ những kiến thức và trải nghiệm đặc biệt với du khách.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Vũ Thị Ngọc',
                'avatar' => 'path/to/avatar8.jpg',
                'phone' => '555-8888',
                'email' => 'ngocvu@gmail.com',
                'bio' => 'Vũ Thị Ngọc là một hướng dẫn viên nhiệt huyết và chuyên nghiệp. Với kinh nghiệm phong phú và sự quan tâm tận tâm đến từng chi tiết, Ngọc luôn mang đến cho du khách những trải nghiệm du lịch đáng nhớ và thú vị.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Lê Đức Anh',
                'avatar' => 'path/to/avatar9.jpg',
                'phone' => '555-9999',
                'email' => 'anhle@gmail.com',
                'bio' => 'Lê Đức Anh là một hướng dẫn viên có kinh nghiệm lâu năm và sự am hiểu sâu sắc về lịch sử và văn hóa địa phương. Anh luôn mang đến cho du khách những trải nghiệm tuyệt vời và những kỷ niệm đáng nhớ trong các chuyến đi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Phan Thanh Hà',
                'avatar' => 'path/to/avatar10.jpg',
                'phone' => '555-1010',
                'email' => 'haphan@gmail.com',
                'bio' => 'Phan Thanh Hà là một hướng dẫn viên tận tâm và chuyên nghiệp, luôn mong muốn mang lại cho du khách những trải nghiệm du lịch đặc biệt và đáng nhớ nhất.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Lê Thị Hà',
                'avatar' => 'path/to/avatar14.jpg',
                'phone' => '555-1414',
                'email' => 'hale@gmail.com',
                'bio' => 'Lê Thị Hà là một hướng dẫn viên chuyên nghiệp với kinh nghiệm dẫn tour đa dạng và sự am hiểu sâu rộng về văn hóa địa phương. Với sự quan tâm tận tâm và tình yêu với nghề, Hà luôn cố gắng mang đến cho du khách những trải nghiệm tuyệt vời nhất.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Nguyễn Văn Phúc',
                'avatar' => 'path/to/avatar15.jpg',
                'phone' => '555-1515',
                'email' => 'phucnguyen@gmail.com',
                'bio' => 'Nguyễn Văn Phúc là một hướng dẫn viên tận tâm và có kinh nghiệm trong lĩnh vực du lịch. Anh có khả năng giao tiếp xuất sắc và luôn cố gắng mang đến cho du khách những trải nghiệm du lịch đáng nhớ và ý nghĩa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('tour_guides')->insert($tourGuides);
        $this->info('Seeded tour_guides table successfully.');
    }

    /**
     * Seed data for tours table
     *
     * @return void
     */
    private function seedToursTable()
    {
        $tours = [
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 9,
                'guide_id' => 9,
                'name' => 'Khám Phá Hồ Hoàn Kiếm',
                'description' => 'Tham quan Hồ Hoàn Kiếm và khu phố cổ Hà Nội với các điểm đến lịch sử và văn hóa.',
                'price' => 900,
                'number_of_participants' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Văn Miếu - Quốc Tử Giám',
                'description' => 'Khám phá Văn Miếu - Quốc Tử Giám, nơi lưu giữ di sản văn hóa và lịch sử của Việt Nam.',
                'price' => 950,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 2,
                'guide_id' => 2,
                'name' => 'Khám Phá Lăng Bác',
                'description' => 'Tham quan Lăng Chủ tịch Hồ Chí Minh và các di tích liên quan để hiểu thêm về lịch sử Việt Nam.',
                'price' => 1000,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 3,
                'guide_id' => 3,
                'name' => 'Tour Chùa Một Cột',
                'description' => 'Khám phá chùa Một Cột, một trong những di tích nổi tiếng và đặc trưng của Hà Nội.',
                'price' => 850,
                'number_of_participants' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 4,
                'guide_id' => 4,
                'name' => 'Khám Phá Nhà Hát Lớn Hà Nội',
                'description' => 'Tham quan Nhà Hát Lớn Hà Nội, nơi tổ chức các sự kiện văn hóa và nghệ thuật quan trọng.',
                'price' => 1050,
                'number_of_participants' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 5,
                'guide_id' => 9,
                'name' => 'Tour Hồ Tây - Chùa Trấn Quốc',
                'description' => 'Khám phá Hồ Tây và chùa Trấn Quốc với các hoạt động tham quan và thư giãn bên hồ.',
                'price' => 900,
                'number_of_participants' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 6,
                'guide_id' => 9,
                'name' => 'Khám Phá Bảo Tàng Dân Tộc Học',
                'description' => 'Tham quan Bảo Tàng Dân Tộc Học để tìm hiểu về các dân tộc và văn hóa đặc trưng của Việt Nam.',
                'price' => 950,
                'number_of_participants' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 7,
                'guide_id' => 7,
                'name' => 'Tour Cổ Loa - Di tích Cổ Loa',
                'description' => 'Khám phá khu di tích Cổ Loa với các hoạt động tham quan và tìm hiểu về lịch sử cổ đại.',
                'price' => 1000,
                'number_of_participants' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 8,
                'guide_id' => 9,
                'name' => 'Khám Phá Phố Cổ Hà Nội',
                'description' => 'Tham quan phố cổ Hà Nội với các hoạt động mua sắm và trải nghiệm ẩm thực truyền thống.',
                'price' => 850,
                'number_of_participants' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 9,
                'guide_id' => 9,
                'name' => 'Tour Hồ Hoàn Kiếm và Đêm Hà Nội',
                'description' => 'Khám phá Hồ Hoàn Kiếm và thưởng thức đêm Hà Nội với các hoạt động giải trí và ẩm thực.',
                'price' => 1100,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Khu Ảo Hồ Tây',
                'description' => 'Trải nghiệm khu ảo Hồ Tây với các hoạt động giải trí và khám phá thiên nhiên.',
                'price' => 950,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Trung Tâm Thành Phố',
                'description' => 'Tham quan các điểm nổi bật của trung tâm thành phố Hồ Chí Minh như Nhà Thờ Đức Bà, Dinh Độc Lập.',
                'price' => 950,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Chợ Bến Thành và Phố Tây Bùi Viện',
                'description' => 'Khám phá chợ Bến Thành và phố Tây Bùi Viện, nơi bạn có thể trải nghiệm mua sắm và ẩm thực đường phố.',
                'price' => 800,
                'number_of_participants' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Khu Du Lịch Đại Nam',
                'description' => 'Tham quan khu du lịch Đại Nam với các hoạt động giải trí và tham quan công viên giải trí.',
                'price' => 1200,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Nhà Hát Lớn và Bảo Tàng Chứng Tích Chiến Tranh',
                'description' => 'Khám phá Nhà Hát Lớn và Bảo Tàng Chứng Tích Chiến Tranh để tìm hiểu về lịch sử và văn hóa.',
                'price' => 1100,
                'number_of_participants' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Khu Du Lịch Suối Tiên',
                'description' => 'Trải nghiệm khu du lịch Suối Tiên với các hoạt động giải trí và tham quan các công trình văn hóa.',
                'price' => 950,
                'number_of_participants' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Củ Chi - Địa Đạo Củ Chi',
                'description' => 'Khám phá Địa Đạo Củ Chi để tìm hiểu về lịch sử chiến tranh và các công trình quân sự.',
                'price' => 1000,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Khu Du Lịch Vườn Cò',
                'description' => 'Tham quan khu du lịch Vườn Cò với các hoạt động thư giãn và chiêm ngưỡng cảnh quan thiên nhiên.',
                'price' => 950,
                'number_of_participants' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Vinhomes Central Park',
                'description' => 'Khám phá khu đô thị Vinhomes Central Park với các tiện ích hiện đại và cảnh quan xanh.',
                'price' => 800,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Khu Du Lịch Bình Quới',
                'description' => 'Trải nghiệm các hoạt động giải trí và thưởng thức ẩm thực tại khu du lịch Bình Quới.',
                'price' => 900,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Phố Đi Bộ Nguyễn Huệ',
                'description' => 'Tham quan phố đi bộ Nguyễn Huệ và thưởng thức các hoạt động giải trí và ẩm thực đường phố.',
                'price' => 850,
                'number_of_participants' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 2,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Bảo Tàng Thành Phố Hồ Chí Minh',
                'description' => 'Khám phá Bảo Tàng Thành Phố Hồ Chí Minh để tìm hiểu về lịch sử và văn hóa địa phương.',
                'price' => 900,
                'number_of_participants' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Kỳ nghỉ Hà Nội - Sapa',
                'description' => 'Khám phá vẻ đẹp hùng vĩ của Sapa với những thửa ruộng bậc thang và các dân tộc thiểu số.',
                'price' => 1200,
                'number_of_participants' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 2,
                'vehicle_id' => 2,
                'guide_id' => 2,
                'name' => 'Khám Phá Bà Nà Hills',
                'description' => 'Chinh phục đỉnh Bà Nà Hills và thưởng thức vẻ đẹp hùng vĩ của thiên nhiên.',
                'price' => 1000,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 3,
                'vehicle_id' => 3,
                'guide_id' => 3,
                'name' => 'Tour Cù Lao Chàm',
                'description' => 'Trải nghiệm vẻ đẹp hoang sơ và nước biển trong xanh của Cù Lao Chàm.',
                'price' => 800,
                'number_of_participants' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 4,
                'vehicle_id' => 4,
                'guide_id' => 4,
                'name' => 'Khám Phá Hội An',
                'description' => 'Khám phá phố cổ Hội An với các kiến trúc cổ kính và văn hóa độc đáo.',
                'price' => 900,
                'number_of_participants' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 5,
                'vehicle_id' => 5,
                'guide_id' => 5,
                'name' => 'Tour Đèo Hải Vân',
                'description' => 'Hành trình khám phá Đèo Hải Vân với cảnh đẹp tuyệt vời và không khí trong lành.',
                'price' => 1100,
                'number_of_participants' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 6,
                'vehicle_id' => 6,
                'guide_id' => 6,
                'name' => 'Khám Phá Sơn Trà',
                'description' => 'Khám phá núi Sơn Trà với cảnh đẹp tựa tranh vẽ và các hoạt động thể thao ngoài trời.',
                'price' => 950,
                'number_of_participants' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 7,
                'vehicle_id' => 7,
                'guide_id' => 7,
                'name' => 'Tham Quan Ngũ Hành Sơn',
                'description' => 'Khám phá hệ thống núi Ngũ Hành Sơn với các chùa chiền và động đá vôi đặc sắc.',
                'price' => 850,
                'number_of_participants' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 8,
                'vehicle_id' => 8,
                'guide_id' => 8,
                'name' => 'Tour Làng Nghề Đà Nẵng',
                'description' => 'Khám phá các làng nghề truyền thống của Đà Nẵng với các sản phẩm thủ công độc đáo.',
                'price' => 750,
                'number_of_participants' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 9,
                'vehicle_id' => 9,
                'guide_id' => 9,
                'name' => 'Khám Phá Suối Mơ',
                'description' => 'Trải nghiệm vẻ đẹp của Suối Mơ và tận hưởng không khí trong lành, mát mẻ.',
                'price' => 980,
                'number_of_participants' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Bãi Bắc',
                'description' => 'Thư giãn tại bãi Bắc với bãi biển tuyệt đẹp và các hoạt động giải trí thú vị.',
                'price' => 1020,
                'number_of_participants' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 3,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Hòn Kê',
                'description' => 'Khám phá Hòn Kê với vẻ đẹp tự nhiên và các hoạt động vui chơi giải trí ngoài trời.',
                'price' => 890,
                'number_of_participants' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 4,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Phố Cổ Hội An',
                'description' => 'Khám phá vẻ đẹp lịch sử và văn hóa của phố cổ Hội An với các kiến trúc cổ kính.',
                'price' => 850,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 4,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Cù Lao Chàm',
                'description' => 'Trải nghiệm vẻ đẹp hoang sơ của Cù Lao Chàm với các bãi biển trong xanh và san hô.',
                'price' => 950,
                'number_of_participants' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 4,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 4,
                'name' => 'Khám Phá Làng Gốm Thanh Hà',
                'description' => 'Tham quan làng gốm Thanh Hà và tìm hiểu quy trình sản xuất gốm truyền thống.',
                'price' => 750,
                'number_of_participants' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 4,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Bãi Biển An Bàng',
                'description' => 'Thư giãn tại bãi biển An Bàng với cát trắng và nước biển trong xanh.',
                'price' => 800,
                'number_of_participants' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 4,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 6,
                'name' => 'Khám Phá Rừng Dừa Bảy Mẫu',
                'description' => 'Trải nghiệm đi thuyền trên sông và khám phá rừng dừa Bảy Mẫu với hệ sinh thái phong phú.',
                'price' => 900,
                'number_of_participants' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 4,
                'hotel_id' => 17,
                'vehicle_id' => 17,
                'guide_id' => 17,
                'name' => 'Tour Làng Hội An',
                'description' => 'Khám phá các làng nghề truyền thống như làng mộc Kim Bồng và làng dệt Thanh Hà.',
                'price' => 780,
                'number_of_participants' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 4,
                'hotel_id' => 18,
                'vehicle_id' => 18,
                'guide_id' => 18,
                'name' => 'Khám Phá Khu Đô Thị Mới Hội An',
                'description' => 'Khám phá các khu đô thị mới phát triển và các dự án lớn tại Hội An.',
                'price' => 850,
                'number_of_participants' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 4,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Chợ Hội An',
                'description' => 'Tham quan chợ Hội An và trải nghiệm mua sắm các sản phẩm địa phương.',
                'price' => 730,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 4,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Văn Hóa Hội An',
                'description' => 'Tìm hiểu về văn hóa và lịch sử của Hội An qua các điểm di tích và bảo tàng.',
                'price' => 920,
                'number_of_participants' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 4,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Lịch Sử Hội An',
                'description' => 'Khám phá các di tích lịch sử nổi tiếng của Hội An và hiểu về quá trình phát triển của thành phố.',
                'price' => 850,
                'number_of_participants' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Kinh Thành Huế',
                'description' => 'Khám phá kinh thành Huế, di sản văn hóa thế giới với các cung điện và lăng tẩm hoàng gia.',
                'price' => 900,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Lăng Cô',
                'description' => 'Trải nghiệm vẻ đẹp của bãi biển Lăng Cô với cát trắng và nước biển trong xanh.',
                'price' => 850,
                'number_of_participants' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Chùa Thiên Mụ',
                'description' => 'Tham quan chùa Thiên Mụ, một trong những ngôi chùa cổ kính và nổi tiếng của Huế.',
                'price' => 800,
                'number_of_participants' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Lăng Khải Định',
                'description' => 'Khám phá lăng Khải Định với kiến trúc độc đáo và các họa tiết tinh xảo.',
                'price' => 950,
                'number_of_participants' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Huế Ban Đêm',
                'description' => 'Trải nghiệm vẻ đẹp của thành phố Huế vào ban đêm với các hoạt động và món ăn đặc sắc.',
                'price' => 780,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Vườn Quốc Gia Bạch Mã',
                'description' => 'Khám phá vườn quốc gia Bạch Mã với hệ sinh thái phong phú và các hoạt động đi bộ đường dài.',
                'price' => 1000,
                'number_of_participants' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tham Quan Làng Đất Sét',
                'description' => 'Khám phá làng đất sét với các sản phẩm thủ công và nghệ thuật đặc sắc.',
                'price' => 800,
                'number_of_participants' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Đầm Phong',
                'description' => 'Khám phá đầm Phong với cảnh đẹp và các hoạt động giải trí thú vị.',
                'price' => 850,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Hồ Tịnh Tâm',
                'description' => 'Tham quan hồ Tịnh Tâm với cảnh quan yên bình và không khí trong lành.',
                'price' => 700,
                'number_of_participants' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Làng Nghề Hương',
                'description' => 'Khám phá làng nghề truyền thống của Huế với các sản phẩm thủ công độc đáo.',
                'price' => 750,
                'number_of_participants' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 5,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Bãi Cát Vàng',
                'description' => 'Trải nghiệm vẻ đẹp của bãi cát vàng với các hoạt động thể thao biển và thư giãn.',
                'price' => 900,
                'number_of_participants' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Đảo Hòn Tằm',
                'description' => 'Trải nghiệm vẻ đẹp của đảo Hòn Tằm với các hoạt động thể thao nước và thư giãn trên bãi biển.',
                'price' => 1050,
                'number_of_participants' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Vinpearl Land',
                'description' => 'Tham quan Vinpearl Land với các trò chơi giải trí và công viên nước tuyệt vời.',
                'price' => 1200,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Đảo Con Sẻ Tre',
                'description' => 'Trải nghiệm vẻ đẹp hoang sơ của đảo Con Sẻ Tre với bãi biển trong xanh và các hoạt động lặn biển.',
                'price' => 950,
                'number_of_participants' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Tháp Bà Ponagar',
                'description' => 'Khám phá tháp Bà Ponagar, di tích lịch sử và văn hóa của người Chăm tại Nha Trang.',
                'price' => 800,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Chợ Đêm Nha Trang',
                'description' => 'Trải nghiệm không khí sôi động của chợ đêm Nha Trang và thưởng thức các món ăn đặc sản.',
                'price' => 700,
                'number_of_participants' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Lặn Biển Hòn Mun',
                'description' => 'Khám phá thế giới dưới nước tại Hòn Mun với các hoạt động lặn biển và ngắm san hô.',
                'price' => 1100,
                'number_of_participants' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Hòn Tre',
                'description' => 'Trải nghiệm vẻ đẹp của Hòn Tre với các hoạt động giải trí và thư giãn trên bãi biển.',
                'price' => 950,
                'number_of_participants' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Suối Tiên',
                'description' => 'Khám phá suối Tiên với cảnh quan thiên nhiên và các hoạt động dã ngoại thú vị.',
                'price' => 800,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Bãi Dài',
                'description' => 'Trải nghiệm vẻ đẹp của bãi Dài với bãi biển dài và nước biển trong xanh.',
                'price' => 850,
                'number_of_participants' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Hòn Chồng',
                'description' => 'Khám phá Hòn Chồng với các bãi đá và cảnh quan tuyệt đẹp.',
                'price' => 750,
                'number_of_participants' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 6,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Hòn Ngọc Việt',
                'description' => 'Trải nghiệm vẻ đẹp của Hòn Ngọc Việt với các hoạt động vui chơi và thư giãn.',
                'price' => 1000,
                'number_of_participants' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Cao Nguyên Đá Đồng Văn',
                'description' => 'Trải nghiệm vẻ đẹp hoang sơ của cao nguyên đá Đồng Văn với cảnh quan hùng vĩ và các làng bản dân tộc.',
                'price' => 1300,
                'number_of_participants' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Mèo Vạc - Lũng Cú',
                'description' => 'Khám phá Mèo Vạc và Lũng Cú với các điểm đến nổi tiếng như cột cờ Lũng Cú và thị trấn Mèo Vạc.',
                'price' => 1400,
                'number_of_participants' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Hoàng Su Phì',
                'description' => 'Trải nghiệm vẻ đẹp của ruộng bậc thang Hoàng Su Phì với những cánh đồng xanh mướt và phong cảnh tuyệt đẹp.',
                'price' => 1200,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Yên Minh - Quản Bạ',
                'description' => 'Khám phá vẻ đẹp của Yên Minh và Quản Bạ với các điểm đến nổi tiếng như đèo Mã Pí Lèng và thung lũng Sủng Là.',
                'price' => 1150,
                'number_of_participants' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Phố Cáo - Sủng Là',
                'description' => 'Trải nghiệm cuộc sống của các dân tộc tại Phố Cáo và Sủng Là với các bản làng cổ kính và phong tục tập quán đặc sắc.',
                'price' => 1250,
                'number_of_participants' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Đường Thôn',
                'description' => 'Khám phá các con đường thôn bản của Hà Giang với cảnh quan tuyệt đẹp và những trải nghiệm văn hóa độc đáo.',
                'price' => 1100,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Cột Cờ Lũng Cú',
                'description' => 'Trải nghiệm vẻ đẹp của cột cờ Lũng Cú, điểm cực Bắc của Việt Nam với cảnh quan hùng vĩ.',
                'price' => 900,
                'number_of_participants' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Cầu Mè - Tả Phìn',
                'description' => 'Khám phá Cầu Mè và Tả Phìn với cảnh quan thiên nhiên tuyệt đẹp và các hoạt động khám phá thú vị.',
                'price' => 950,
                'number_of_participants' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Thị Trấn Đồng Văn',
                'description' => 'Trải nghiệm sự nhộn nhịp và vẻ đẹp của thị trấn Đồng Văn, nơi nổi tiếng với các chợ phiên và phong tục tập quán.',
                'price' => 1000,
                'number_of_participants' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Thôn Nà Khương',
                'description' => 'Khám phá thôn Nà Khương với các hoạt động du lịch cộng đồng và trải nghiệm văn hóa của người dân địa phương.',
                'price' => 850,
                'number_of_participants' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Hồ Ba Bể',
                'description' => 'Trải nghiệm vẻ đẹp của hồ Ba Bể với các hoạt động chèo thuyền và tham quan các điểm du lịch xung quanh.',
                'price' => 1250,
                'number_of_participants' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 7,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Làng Văn Hóa',
                'description' => 'Khám phá các làng văn hóa dân tộc của Hà Giang với các phong tục và tập quán truyền thống đặc sắc.',
                'price' => 950,
                'number_of_participants' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Đảo Ngọc Phú Quốc',
                'description' => 'Trải nghiệm vẻ đẹp của đảo Ngọc với bãi biển trắng mịn và nước biển trong xanh.',
                'price' => 1500,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour VinWonders Phú Quốc',
                'description' => 'Khám phá VinWonders với các trò chơi giải trí và công viên nước tuyệt vời.',
                'price' => 1400,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Đảo Hon Thom',
                'description' => 'Trải nghiệm vẻ đẹp hoang sơ của đảo Hon Thom với các hoạt động thể thao nước và thư giãn trên bãi biển.',
                'price' => 1350,
                'number_of_participants' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Dinh Cậu và Chợ Đêm Phú Quốc',
                'description' => 'Khám phá Dinh Cậu và thưởng thức các món ăn đặc sản tại chợ đêm Phú Quốc.',
                'price' => 1100,
                'number_of_participants' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Vườn Tiêu và Nhà Thùng',
                'description' => 'Tham quan vườn tiêu và nhà thùng để hiểu hơn về quá trình sản xuất tiêu và nước mắm.',
                'price' => 950,
                'number_of_participants' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Lặn Biển Hòn Móng Tay',
                'description' => 'Khám phá thế giới dưới nước tại Hòn Móng Tay với các hoạt động lặn biển và ngắm san hô.',
                'price' => 1250,
                'number_of_participants' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Bãi Sao',
                'description' => 'Trải nghiệm bãi Sao với cát trắng mịn và nước biển trong xanh, lý tưởng cho việc thư giãn và tắm biển.',
                'price' => 1050,
                'number_of_participants' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Câu Cá và Ngắm Hoàng Hôn',
                'description' => 'Tham gia tour câu cá và ngắm hoàng hôn tuyệt đẹp trên biển Phú Quốc.',
                'price' => 1150,
                'number_of_participants' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Suối Tranh',
                'description' => 'Trải nghiệm vẻ đẹp của Suối Tranh với cảnh quan thiên nhiên và hoạt động dã ngoại.',
                'price' => 950,
                'number_of_participants' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Khám Phá Đảo Dăm Ngang',
                'description' => 'Khám phá đảo Dăm Ngang với cảnh quan hoang sơ và các hoạt động khám phá thú vị.',
                'price' => 1200,
                'number_of_participants' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 8,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Công Viên Quốc Gia Phú Quốc',
                'description' => 'Trải nghiệm các hoạt động và điểm tham quan trong công viên quốc gia Phú Quốc.',
                'price' => 1300,
                'number_of_participants' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Sapa',
                'description' => 'Trải nghiệm vẻ đẹp của Sapa với những thửa ruộng bậc thang xanh mướt và các bản làng dân tộc.',
                'price' => 1400,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Fansipan - Nóc Nhà Đông Dương',
                'description' => 'Chinh phục đỉnh Fansipan và tận hưởng cảnh quan hùng vĩ của dãy Hoàng Liên Sơn.',
                'price' => 2000,
                'number_of_participants' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Thị Trấn Bắc Hà',
                'description' => 'Khám phá thị trấn Bắc Hà với chợ phiên đặc sắc và các hoạt động văn hóa của người dân địa phương.',
                'price' => 1100,
                'number_of_participants' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Cát Cát - Lao Chải',
                'description' => 'Tham quan bản Cát Cát và Lao Chải với các hoạt động trekking và trải nghiệm văn hóa bản địa.',
                'price' => 1300,
                'number_of_participants' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Bản Tả Phìn',
                'description' => 'Trải nghiệm cuộc sống của người dân bản Tả Phìn với các hoạt động dã ngoại và tìm hiểu phong tục tập quán.',
                'price' => 1050,
                'number_of_participants' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Đồi Chè Ô Long',
                'description' => 'Khám phá các đồi chè Ô Long với phong cảnh thiên nhiên tuyệt đẹp và tìm hiểu quy trình sản xuất chè.',
                'price' => 950,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Dinh Thự Họ Vương',
                'description' => 'Tham quan dinh thự Họ Vương với kiến trúc độc đáo và tìm hiểu về lịch sử gia đình họ Vương.',
                'price' => 1150,
                'number_of_participants' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Sa Pa - Lao Chải - Tả Van',
                'description' => 'Khám phá các bản làng Sa Pa như Lao Chải và Tả Van với các hoạt động trekking và hòa mình vào thiên nhiên.',
                'price' => 1200,
                'number_of_participants' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Thác Bạc',
                'description' => 'Trải nghiệm vẻ đẹp của thác Bạc với không gian thiên nhiên trong lành và hoạt động dã ngoại thú vị.',
                'price' => 950,
                'number_of_participants' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Làng Văn Hóa Hmong',
                'description' => 'Khám phá văn hóa và phong tục của người Hmong tại các làng bản quanh Sapa.',
                'price' => 1050,
                'number_of_participants' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 9,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Cổng Trời Sapa',
                'description' => 'Trải nghiệm vẻ đẹp hùng vĩ từ Cổng Trời Sapa với tầm nhìn bao quát toàn cảnh vùng núi.',
                'price' => 950,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Vịnh Hạ Long',
                'description' => 'Trải nghiệm vẻ đẹp kỳ vĩ của Vịnh Hạ Long với các hoạt động tham quan và du thuyền.',
                'price' => 1600,
                'number_of_participants' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Đảo Cô Tô',
                'description' => 'Khám phá vẻ đẹp của đảo Cô Tô với bãi biển trong xanh và các hoạt động thư giãn.',
                'price' => 1500,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Khám Phá Đảo Quan Lạn',
                'description' => 'Trải nghiệm những bãi biển hoang sơ và cảnh đẹp của đảo Quan Lạn.',
                'price' => 1400,
                'number_of_participants' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' => 1,
                'name' => 'Tour Hang Sửng Sốt',
                'description' => 'Khám phá hang Sửng Sốt với các hình thù đá độc đáo và cảnh quan kỳ thú.',
                'price' => 1200,
                'number_of_participants' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' =>1,
                'name' => 'Khám Phá Làng Chài Vung Viêng',
                'description' => 'Trải nghiệm cuộc sống của người dân làng chài và thưởng thức hải sản tươi ngon.',
                'price' => 1100,
                'number_of_participants' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' =>1,
                'name' => 'Tour Hạ Long - Tinh Hoa Di Sản',
                'description' => 'Khám phá các điểm đến nổi bật của Hạ Long với các hoạt động tham quan và giải trí.',
                'price' => 1250,
                'number_of_participants' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' =>1,
                'name' => 'Khám Phá Đảo Ngọc Vạn Cảnh',
                'description' => 'Trải nghiệm các hoạt động trên đảo Ngọc Vạn Cảnh với cảnh quan thiên nhiên và bãi biển tuyệt đẹp.',
                'price' => 1300,
                'number_of_participants' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' =>1,
                'name' => 'Tour Hang Luồn - Hồ Ba Hạ',
                'description' => 'Khám phá hang Luồn và hồ Ba Hạ với các hoạt động khám phá và thư giãn.',
                'price' => 1150,
                'number_of_participants' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' =>1,
                'name' => 'Khám Phá Đảo Hạ Long',
                'description' => 'Tham quan đảo Hạ Long với các hoạt động chèo thuyền và tham quan các bãi biển đẹp.',
                'price' => 1400,
                'number_of_participants' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' =>1,
                'name' => 'Tour Cảng Cái Rồng',
                'description' => 'Khám phá cảng Cái Rồng và các khu vực lân cận với các hoạt động tham quan và thư giãn.',
                'price' => 1100,
                'number_of_participants' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 10,
                'hotel_id' => 1,
                'vehicle_id' => 1,
                'guide_id' =>1,
                'name' => 'Khám Phá Hang Đầu Gỗ',
                'description' => 'Trải nghiệm vẻ đẹp hùng vĩ của hang Đầu Gỗ với các hình thù đá độc đáo.',
                'price' => 1250,
                'number_of_participants' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('tours')->insert($tours);
        $this->info('Seeded tours table successfully.');
    }

    /**
     * Seed data for tour_images table
     *
     * @return void
     */
    private function seedTourImagesTable()
    {
        $tourImages = [
            [
                'tour_id' => 1,
                'image' => 'path/to/image1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('tour_images')->insert($tourImages);
        $this->info('Seeded tour_images table successfully.');
    }

    
    private function seedTourDatesTable()
    {
        $tourDates = [];
        $startYear = 2024;
        $endYear = 2026;
        
        for ($i = 148; $i <= 257; $i++) {
            $startMonth = rand(1, 12);
            $startDay = rand(1, 28); // Để đảm bảo không vượt quá số ngày trong tháng
            $endMonth = $startMonth;
            $endDay = $startDay + rand(1, 7); // Ngày kết thúc sau ít nhất 1 ngày và tối đa 7 ngày
        
            if ($endDay > 28) {
                $endDay = 28; // Giới hạn ngày kết thúc là 28 để tránh lỗi ngày tháng
            }
        
            $startDate = "$startYear-$startMonth-$startDay";
            $endDate = "$startYear-$endMonth-$endDay";
        
            $tourDates[] = [
                'tour_id' => $i,
                'start_date' => $startDate,
                'end_date' => $endDate,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('tour_dates')->insert($tourDates);
        $this->info('Seeded tour_dates table successfully.');
    }
}